function Education(props) {
	return (
		<section>
			<h3>Education</h3>
			<form>
				<label>
					<input
						type='text'
						id='university'
						name='university'
						placeholder='University'
						value={props.data.university}
						onChange={props.handleInput}
					/>
				</label>
				<label>
					<input
						type='text'
						id='universityCity'
						name='universityCity'
						placeholder='City'
						value={props.data.universityCity}
						onChange={props.handleInput}
					/>
				</label>
				<label>
					<input
						type='text'
						id='degree'
						name='degree'
						placeholder='Degree'
						value={props.data.degree}
						onChange={props.handleInput}
					/>
				</label>
				<label>
					<input
						type='text'
						id='subject'
						name='subject'
						placeholder='Subject'
						value={props.data.subject}
						onChange={props.handleInput}
					/>
				</label>
				<label>
					<input
						type='date'
						id='universityStarted'
						name='universityStarted'
						placeholder='Started'
						min='1950-01-01'
						max='2020-01-01'
						value={props.data.universityStarted}
						onChange={props.handleInput}
					/>
				</label>
				<label>
					<input
						type='date'
						id='universityEnded'
						name='universityEnded'
						placeholder='Ended'
						min='1950-01-01'
						max='2020-01-01'
						value={props.data.universityEnded}
						onChange={props.handleInput}
					/>
				</label>
				<button type='submit'>Submit</button>
			</form>
		</section>
	);
}

export default Education;
