function Experience(props) {
	return (
		<section>
			<h3>Experience</h3>
			<form>
				<label>
					<input
						type='text'
						id='company'
						name='company'
						placeholder='Company'
						value={props.data.company}
						onChange={props.handleInput}
					/>
				</label>
				<label>
					<input
						type='text'
						id='position'
						name='position'
						placeholder='Position'
						value={props.data.position}
						onChange={props.handleInput}
					/>
				</label>
				<label>
					<input
						type='text'
						id='city'
						name='city'
						placeholder='City'
						value={props.data.city}
						onChange={props.handleInput}
					/>
				</label>
				<label>
					<input
						type='date'
						id='workStarted'
						name='workStarted'
						placeholder='Started'
						min='1950-01-01'
						max='2020-01-01'
						value={props.data.workStarted}
						onChange={props.handleInput}
					/>
				</label>
				<label>
					<input
						type='date'
						id='workEnded'
						name='workEnded'
						placeholder='Ended'
						min='1950-01-01'
						max='2020-01-01'
						value={props.data.workEnded}
						onChange={props.handleInput}
					/>
				</label>
				<button type='submit'>Submit</button>
			</form>
		</section>
	);
}

export default Experience;
